# Generated by Django 6.0 on 2026-01-03 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coach',
            field=models.ForeignKey(blank=True, help_text='The coach assigned to this athlete', limit_choices_to={'role': 'Coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='users.userprofile'),
        ),
    ]
