# Generated by Django 6.0 on 2025-12-14 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_type', models.CharField(choices=[('training', 'Training Day'), ('competition', 'Competition Day'), ('rest', 'Rest Day')], max_length=20)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('timing', models.CharField(choices=[('pre_training', 'Pre-Training'), ('post_training', 'Post-Training'), ('general', 'General')], max_length=20)),
                ('carbohydrates_g', models.FloatField(help_text='Carbohydrates in grams')),
                ('protein_g', models.FloatField(help_text='Protein in grams')),
                ('fats_g', models.FloatField(help_text='Fats in grams')),
                ('hydration_liters', models.FloatField(help_text='Hydration in liters')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
