# Generated by Django 6.0 on 2026-02-04 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('carbs_per_100g', models.FloatField(help_text='Carbs in grams per 100g')),
                ('protein_per_100g', models.FloatField(help_text='Protein in grams per 100g')),
                ('fats_per_100g', models.FloatField(help_text='Fats in grams per 100g')),
            ],
        ),
        migrations.AddField(
            model_name='nutritionlog',
            name='quantity_g',
            field=models.FloatField(blank=True, help_text='Quantity in grams (if food item selected)', null=True),
        ),
        migrations.AddField(
            model_name='nutritionlog',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.fooditem'),
        ),
    ]
