# Generated by Django 6.0 on 2026-02-05 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_fooditem_nutritionlog_quantity_g_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_g', models.FloatField(help_text='Quantity in grams')),
                ('carbohydrates_g', models.FloatField(help_text='Carbohydrates in grams')),
                ('protein_g', models.FloatField(help_text='Protein in grams')),
                ('fats_g', models.FloatField(help_text='Fats in grams')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.fooditem')),
                ('nutrition_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meals.nutritionlog')),
            ],
        ),
    ]
