# Generated by Django 6.0 on 2026-02-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_nutritionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionlog',
            name='total_calories',
            field=models.FloatField(default=0, help_text='Total calories consumed'),
        ),
    ]
