# Generated by Django 6.0 on 2026-02-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_nutritionlog_total_calories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='fooditem',
            name='calories_per_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('solid', 'Solid'), ('liquid', 'Liquid'), ('piece', 'Piece')], default='solid', max_length=10),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='region',
            field=models.CharField(choices=[('global', 'Global'), ('kerala', 'Kerala')], default='global', max_length=10),
        ),
    ]
