# Generated by Django 6.0 on 2025-12-14 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('discipline', models.CharField(choices=[('100m', '100m Sprint'), ('200m', '200m Sprint'), ('400m', '400m Sprint'), ('800m', '800m Run'), ('1500m', '1500m Run'), ('long_jump', 'Long Jump'), ('high_jump', 'High Jump'), ('triple_jump', 'Triple Jump'), ('shot_put', 'Shot Put'), ('discus', 'Discus Throw'), ('javelin', 'Javelin Throw'), ('hammer', 'Hammer Throw')], max_length=20)),
                ('session_type', models.CharField(choices=[('training', 'Training'), ('competition', 'Competition'), ('recovery', 'Recovery')], default='training', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThrowerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implement_weight_kg', models.FloatField(help_text='Weight of implement in kg')),
                ('attempts', models.IntegerField(default=1)),
                ('best_throw_m', models.FloatField(help_text='Best result in meters')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workouts.trainingsession')),
            ],
        ),
        migrations.CreateModel(
            name='RunnerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_m', models.FloatField(help_text='Distance in meters (e.g., 100, 200)')),
                ('time_seconds', models.FloatField(help_text='Time in seconds')),
                ('repetitions', models.IntegerField(default=1, help_text='Number of reps')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workouts.trainingsession')),
            ],
        ),
        migrations.CreateModel(
            name='JumperSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=1)),
                ('best_jump_m', models.FloatField(help_text='Best result in meters')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workouts.trainingsession')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkoutLog',
        ),
    ]
