# Generated by Django 6.0 on 2025-12-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_trainingsession_throwersession_runnersession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='athlete_type',
            field=models.CharField(choices=[('runner', 'Runner'), ('jumper', 'Jumper'), ('thrower', 'Thrower')], default='runner', max_length=20),
            preserve_default=False,
        ),
    ]
