# Generated by Django 6.0 on 2026-02-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_trainingsession_athlete_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='calories_burned',
            field=models.FloatField(default=0, help_text='Calories burned in this session'),
        ),
    ]
