# Generated by Django 6.0 on 2026-02-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_trainingsession_calories_burned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='athlete_type',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='duration_minutes',
            field=models.FloatField(default=0, help_text='Duration of session in minutes'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='intensity',
            field=models.CharField(choices=[('Low', 'Low (MET 4)'), ('Moderate', 'Moderate (MET 7)'), ('High', 'High (MET 10)')], default='Moderate', max_length=10),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='rpe',
            field=models.IntegerField(default=5, help_text='Rate of Perceived Exertion (1-10)'),
        ),
        migrations.AlterField(
            model_name='runnersession',
            name='distance_m',
            field=models.FloatField(help_text='Distance in meters'),
        ),
        migrations.AlterField(
            model_name='runnersession',
            name='repetitions',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='calories_burned',
            field=models.FloatField(default=0, help_text='Auto-calculated burned calories'),
        ),
    ]
