# Generated by Django 6.0 on 2026-02-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_remove_trainingsession_athlete_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='calories_burned',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='duration_minutes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='intensity',
            field=models.CharField(choices=[('low', 'Low (MET 4)'), ('moderate', 'Moderate (MET 7)'), ('high', 'High (MET 10)')], default='moderate', max_length=10),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='rpe',
            field=models.IntegerField(default=5),
        ),
    ]
