# Generated by Django 6.0 on 2026-02-22 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_alter_trainingsession_calories_burned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='rpe',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
